### ISSUE TITLE
Unable to connect to the external network

### ISSUE THREAD

**Issue by pradp** [pivotal-cf/pcfdev#25]
I have created a user provided service for my redis server running in my host machine.

````
redis://:authkey@192.168.1.6:6379
192.168.1.6 - Host machine ip address
````

I'm able to connect to my redis server from my guest machine.

````
vagrant ssh
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-43-generic x86_64)
 * Documentation:  https://help.ubuntu.com/
Last login: Fri Jan 29 16:36:51 2016 from 10.0.2.2
vagrant@agent-id-micropcf-0:~$ redis-cli -h 192.168.1.6 -p 6379
192.168.1.6:6379>
````

But my spring boot app deployed in my micropcf is unable to connect to above redis server.

````
herServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool] with root cause
2016-01-29T22:23:15.68+0530 [APP/0]      OUT java.net.ConnectException: Connection refused
````

I think there is some network issue with application running within the container to access the external network or is there any other way I should be connecting to the external world for the services?

**Comment by davidwadden** [comment]
@pradp - you'll need to add a security group in order to allow traffic from the app container to the user-provided service running on your host.

i just ran through testing connectivity from spring-music to a redis instance running on my host as follows (replaced in your ip):

```
 ○ → cat > sg.json
   [
     {
       "protocol": "tcp",
       "destination": "192.168.1.6",
       "ports": "6379"
     }
   ]
^D
```

```
○ → cf create-security-group host-redis sg.json
Creating security group host-redis as admin
OK
```

```
○ → cf bind-security-group host-redis micropcf-org micropcf-space
Assigning security group host-redis to space micropcf-space in org micropcf-org as admin...
OK
```

```
○ → cf ssh spring-music -k
vcap@bepbr6nakkq:~$ curl 192.168.1.6:6379
-ERR wrong number of arguments for 'get' command
-ERR unknown command 'User-Agent:'
-ERR unknown command 'Host:'
-ERR unknown command 'Accept:'
```

**Comment by pradp** [comment]
Thanks @davidwadden It worked. I missed the security constraint completely. I have [blogged](https://medium.com/code-tech/pivotal-cloud-foundry-in-laptop-20502c967bf1#.y5uak6ur0) about this project.

**Comment by sclevine** [comment]
Re-opening to indicate that we have feature in the backlog to add a security group for the host.

**Comment by sclevine** [comment]
This feature was completed in February.
