### ISSUE TITLE
MicroPCF doesn't start without Internet connectivity

### ISSUE THREAD

**Issue by debu66er** [pivotal-cf/pcfdev#29]
As requested by @davidwadden in #17 here it is a new issue:
Environment:
MicroPCF 0.5.0
Vagrant 1.8.1
VBox 5.0.14
Windows 7

When I start MicroPCF with Internet connectivity, after 5-6 minutes MicroPCF starts successfully.

If I try to start it without Internet connectivity, it gets stuck at: 
==> default: Waiting for services to start...

After 12-14 minutes it still at that point. And as soon as I plug the ethernet (Internet connectivity) it finishes successfully. If I don't attach the ethernet which not always is possible it never finishes.

Don't know if this is an issue or not. I understand I need Internet connectivity to get a new buildpack or a docker image from the community, but if I just want to test my own things locally with no external interaction, should it work?

**Comment by sclevine** [comment]
Hi @debu66er,

If you start MicroPCF without internet access, the *.local.micropcf.io CNAME will not resolve. This prevents MicroPCF from booting. It's possible to shim out the CNAME with dnsmasq on the host. See [here](http://stackoverflow.com/questions/22313142/wildcard-subdomains-with-dnsmasq).

We have a story in our backlog to address the startup issue by introducing dnsmasq inside the VM.

**Comment by benlaplanche** [comment]
I successfully followed this guide on OSX https://passingcuriosity.com/2013/dnsmasq-dev-osx/

**Comment by MeiyappanKannappa** [comment]
Hi , I have same issue, But I have internet connectivity through proxy. I am able to download vagrant micropcf files through proxy but after that it hangs at**_ ==> default: Waiting for services to start..._** for long time. Can you help me. Many thanks!!!!

**Comment by wgorder** [comment]
+1 not proxy friendly.  Everything fine up to waiting for services to start.

**Comment by jmcolyer** [comment]
+1 on the proxy sticking at "Waiting for services to start."

**Comment by jmcolyer** [comment]
@benlaplanche I tried to follow the guide that you mentioned, but it hangs on "Waiting for services to start...".  If I put vagrant in UI mode, it brings up a login prompt at that point.  Any suggestions?

**Comment by wgorder** [comment]
@sclevine What does the story around this look like?

We are looking at PCF for our enterprise.  This looked promising for improving the dev experience with distributed cloud architectures however its seems impossible to get this to work behind our corporate proxies.  I am not sure if I am missing a step or if that is a use case you do not plan on supporting.

Thanks,

**Comment by wgorder** [comment]
Nvm now I see @davidwadden posted a deprecation notice.  Lattice- > micropcf -> PCF Dev... I am getting dizzy.

I will reach out to our account manager and get the closed beta I guess.  I assume it has feature parity with what this offers..

**Comment by sclevine** [comment]
Hi @wgorder,

Happy to hear that you've found MicroPCF useful! We're working on an early customer access group for the PCF Dev closed beta on Pivnet. We also plan to resume our Github presence very soon. Unlike the product transition from Lattice to MicroPCF, the PCF Dev name change is more of a re-branding with a greater focus on providing PCF functionality locally.

The latest closed beta release of PCF Dev should start behind a proxy, and we have work in flight for more complete support.

Please let us know if you run into any other issues,
Stephen
