### ISSUE TITLE
More FAQs

### ISSUE THREAD

**Issue by drnic** [pivotal-cf/pcfdev#32]
Please add to the FAQ https://github.com/pivotal-cf/micropcf/blob/master/FAQ.md#general-questions 

* Why is this called micropcf rather than microcf?
* Why is this in https://github.com/pivotal-cf rather than https://github.com/cloudfoundry-incubator?
* If it is packaging Pivotal Cloud Foundry (https://github.com/pivotal-cf/micropcf/blob/master/FAQ.md#if-my-application-runs-on-micropcf-will-it-run-on-pcf) rather than OSS Cloud Foundry, what are the differences? Is the Pivotal Web Console app included? What are the licensing restrictions for running micropcf vs running Cloud Foundry Foundation's Apache codebases?

**Comment by Turbots** [comment]
I think this can be closed, since the FAQs have been added

**Comment by sclevine** [comment]
@drnic, now that we've launched PCF Dev, do you still have any questions here?

Note that we plan to include Apps Manager and Spring Cloud Services in the future. While code in is repo is open source, the version of PCF Dev that we distribute via PivNet is a freely available commercial product.

**Comment by drnic** [comment]
Is the VM running bosh-lite and the components' jobs inside that? Or is the VM running the components' jobs directly?

On Mon, May 9, 2016 at 12:41 PM -0700, "Stephen Levine" notifications@github.com wrote:

@drnic, now that we're launched PCF Dev, do you still have any questions here?

Note that we plan to include Apps Manager and Spring Cloud Services in the future. While code in is repo is open source, the version of PCF Dev that we distribute via PivNet is a freely available commercial product.

**Comment by sclevine** [comment]
We're running the components directly, but they're BOSH deployed via [bosh-provisioner](https://github.com/cppforlife/bosh-provisioner). This strategy gives us a fast boot time with little complexity and overhead. It's also very easy to debug, and a good test-case for CF component colocation.

**Comment by drnic** [comment]
Thanks @sclevine
